import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#ffffffff",
        alignItems: "center",
        justifyContent: "center",
    },
    header: {
        alignItems: "center",
        justifyContent: "space-between",
        width: "100%",
        paddingHorizontal: 20,
        paddingTop: 20,
        paddingBottom: 20,
    },
    title: {
        fontSize: 24,
        fontWeight: "bold",
        color: "#000",
        paddingTop: 40,
    },
    subtitle: {
        marginTop: 5,
        fontSize: 16,
        color: "#000",
    },
    inputContainer: {
        flexDirection: "row",
        gap: 10,
        width: "100%",
        paddingHorizontal: 20,
        paddingTop: 20,
        paddingBottom: 20,
    },
    input: {
        flex: 1,
        height: 50,
        backgroundColor: "#f5f5f5",
        borderRadius: 10,
        paddingHorizontal: 10,
        fontSize: 16,
        color: "#000",
    },
    addButton: {
        width: 50,
        height: 50,
        backgroundColor: "#000",
        borderRadius: 10,
        alignItems: "center",
        justifyContent: "center",
    },
    addButtonText: {
        fontSize: 24,
        fontWeight: "bold",
        color: "#fff",
    },
    summaryContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
        width: "100%",
        paddingHorizontal: 20,
        paddingTop: 20,
        paddingBottom: 20,
        gap: 10,
    },
    summaryCard: {
        flex: 1,
        height: 50,
        backgroundColor: "#f5f5f5",
        borderRadius: 10,
        paddingHorizontal: 10,
        fontSize: 16,
        color: "#000",
        alignItems: "center",
        justifyContent: "center",
    },
    summaryText: {
        fontSize: 16,
        color: "#000",
    },
    summaryNumber: {
        fontSize: 16,
        fontWeight: "bold",
        color: "#000",
    },
    summaryLabel: {
        fontSize: 16,
        color: "#000",
    },
    emptyState: {
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
        paddingTop: 20,
        width: "100%",
        paddingHorizontal: 20,
        backgroundColor: "#f5f5f5",
        borderRadius: 10,
        paddingBottom: 20,
    },
    emptyTitle: {
        fontSize: 16,
        color: "#000",
        fontWeight: "bold",
    },
    emptyText: {
        fontSize: 16,
        color: "#000",
        marginTop: 10,
        textAlign: "center",
    },
    list: {
        flex: 1,
        width: "100%",
        paddingHorizontal: 20,
        paddingTop: 20,
        paddingBottom: 20,
    },
    listContent: {
        padding: 20,
        paddingBottom: 40,
        flexGrow: 1,
    },
    itemSeparator: {
        height: 1,
        backgroundColor: "#f5f5f5",
    },
    listHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        width: "100%",
        paddingHorizontal: 20,
        paddingTop: 20,
        paddingBottom: 20,
    },
    listHeaderTitle: {
        fontSize: 27,
        fontWeight: "bold",
        color: "#000",
    },
    taskCard: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#f5f5f5",
        borderRadius: 10,
        paddingHorizontal: 10,
        padding: 14,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: "#ddd",
    },
    taskContent: {
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
    },
    checkCircle: {
        width: 24,
        height: 24,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: "#000",
        alignItems: "center",
        justifyContent: "center",
    },
    checkCircleDone: {
        backgroundColor: "#000",
    },
    checkCircleIcon: {
        fontWeight: "bold",
        color: "#fff",
    },
    taskText: {
        flex: 1,
        fontSize: 16,
        color: "#000",
    },
    taskTextDone: {
        textDecorationLine: "line-through",
        color: "#000",
    },
    deleteButton: {
        width: 40,
        height: 40,
        backgroundColor: "#000",
        borderRadius: 10,
        alignItems: "center",
        justifyContent: "center",
    },
    deleteButtonText: {
        fontSize: 15,
        fontWeight: "bold",
        color: "#fff",
    },



});

export default styles;